
title: Imran Habib - Software Developer

author: Imran Habib

author_email: imranhabib14@gmail.com

url: https://imranhabib.github.io/

permalink: pretty

paginate: 1

exclude: 
- README.md
- .ruby-version
- Gemfile
- Gemfile.lock

# Custom vars
current_version:  1.0.0
repo:             https://github.com/imranhabib/imranhabib.github.io
